# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/FIR_Filter/FIR_Filter.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIR_Filter || ORIG_REF_NAME==FIR_Filter} -quiet] -quiet

# IP: bd/FIR_Filter/ip/FIR_Filter_processing_system7_0_0/FIR_Filter_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIR_Filter_processing_system7_0_0 || ORIG_REF_NAME==FIR_Filter_processing_system7_0_0} -quiet] -quiet

# IP: bd/FIR_Filter/ip/FIR_Filter_nco_dual_ip_0_0/FIR_Filter_nco_dual_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIR_Filter_nco_dual_ip_0_0 || ORIG_REF_NAME==FIR_Filter_nco_dual_ip_0_0} -quiet] -quiet

# IP: bd/FIR_Filter/ip/FIR_Filter_ps7_0_axi_periph_0/FIR_Filter_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIR_Filter_ps7_0_axi_periph_0 || ORIG_REF_NAME==FIR_Filter_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/FIR_Filter/ip/FIR_Filter_rst_ps7_0_100M_0/FIR_Filter_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIR_Filter_rst_ps7_0_100M_0 || ORIG_REF_NAME==FIR_Filter_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/FIR_Filter/ip/FIR_Filter_ila_0_0/FIR_Filter_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIR_Filter_ila_0_0 || ORIG_REF_NAME==FIR_Filter_ila_0_0} -quiet] -quiet

# IP: bd/FIR_Filter/ip/FIR_Filter_auto_pc_0/FIR_Filter_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIR_Filter_auto_pc_0 || ORIG_REF_NAME==FIR_Filter_auto_pc_0} -quiet] -quiet

# XDC: bd/FIR_Filter/FIR_Filter_ooc.xdc
