# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Juanma/Documents/FIR_Filter/Sintesis/FIR_Filter.srcs/sources_1/bd/FIR_Filter/ip/FIR_Filter_ila_0_0/FIR_Filter_ila_0_0.xci
# IP: The module: 'FIR_Filter_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Juanma/Documents/FIR_Filter/Sintesis/FIR_Filter.srcs/sources_1/bd/FIR_Filter/ip/FIR_Filter_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_Filter_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Juanma/Documents/FIR_Filter/Sintesis/FIR_Filter.srcs/sources_1/bd/FIR_Filter/ip/FIR_Filter_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_Filter_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Juanma/Documents/FIR_Filter/Sintesis/FIR_Filter.srcs/sources_1/bd/FIR_Filter/ip/FIR_Filter_ila_0_0/FIR_Filter_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_Filter_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Juanma/Documents/FIR_Filter/Sintesis/FIR_Filter.srcs/sources_1/bd/FIR_Filter/ip/FIR_Filter_ila_0_0/FIR_Filter_ila_0_0.xci
# IP: The module: 'FIR_Filter_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Juanma/Documents/FIR_Filter/Sintesis/FIR_Filter.srcs/sources_1/bd/FIR_Filter/ip/FIR_Filter_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_Filter_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Juanma/Documents/FIR_Filter/Sintesis/FIR_Filter.srcs/sources_1/bd/FIR_Filter/ip/FIR_Filter_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_Filter_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Juanma/Documents/FIR_Filter/Sintesis/FIR_Filter.srcs/sources_1/bd/FIR_Filter/ip/FIR_Filter_ila_0_0/FIR_Filter_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_Filter_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
